apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::463991008443:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-W1JH4BRKORZX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::463991008443:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-02T03:56:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1886"
  uid: f3e67e22-1d85-4fc2-bcf3-d7224a366303
